### ISSUE TITLE
New question: MathJaX

### ISSUE THREAD

**Issue by josephwright** [tex-faq/tex-faq.github.io#1]
A question covering MathJaX (and possible KaTeX) would be useful: it would complement Q-alternatives (and should be linked from there).

**Comment by josephwright** [comment]
Might be covered in something about 'TeX-like' syntax: would also include current MS Word, _etc._

**Comment by davidcarlisle** [comment]
yes I'll take that, and remove the mathjax discussion in the mathml
question and instead reference the new text.

**Comment by davidcarlisle** [comment]
I renamed FAQ-mathml to "Math on the Web" and updated the MathJax description and added a KaTeX section. The Word latex-like input syntax didn't really fit in that context but I'll close for now, we could add an answer about Word input forms if that becomes Frequently asked.
